on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Download Geny and build website
        run: |
          wget https://github.com/Yendric/geny/releases/download/latest/geny
          chmod +x geny
          pnpm install
          ./geny build --run "pnpm run build"

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
